#!/bin/bash

#SCRIPT LEER ARCHIVO PARA CONT LEER ARCHIVO PARA CONVERTIRLO EN MP3
echo "Introduce el archivo que quieres reproducir"
read FILE
echo -e "\033[41m"
cat $FILE | cowsay -f snowman

echo $FILE

FILECUT=`cut $FILE -d "." -f 1`

FILEWAVE=`cat $FILE | text2wave`

FILEMP3=`lame $FILEWAVE`

mpg123 $FILEMP3 $FILECUT.mp3

echo -e "\033[0;30m"
